"""All scenes: (id, title, group). The id is the module name in this folder.

The order here is the order in the web interface and for the button on the board.
"""
SCENES = (
    ("uhr", "Uhr", "Info"),
    ("laufschrift", "Laufschrift", "Info"),
    ("hub_status", "Hub-Status", "Info"),
    ("plasma", "Plasma", "Stimmung"),
    ("feuer", "Kaminfeuer", "Stimmung"),
    ("polarlicht", "Polarlicht", "Stimmung"),
    ("lavalampe", "Lavalampe", "Stimmung"),
    ("atmen", "Atmen", "Stimmung"),
    ("kaleidoskop", "Kaleidoskop", "Stimmung"),
    ("regen", "Regen", "Stimmung"),
    ("sternenhimmel", "Sternenhimmel", "Stimmung"),
    ("sternenflug", "Sternenflug", "Effekte"),
    ("tunnel", "Tunnel", "Effekte"),
    ("matrix", "Matrix-Regen", "Effekte"),
    ("feuerwerk", "Feuerwerk", "Effekte"),
    ("baelle", "Leuchtbälle", "Effekte"),
    ("dna", "DNA-Helix", "Effekte"),
    ("linien", "Linienspiel", "Effekte"),
    ("tetris", "Tetris", "Spiele"),
    ("snake", "Snake", "Spiele"),
    ("pong", "Pong", "Spiele"),
    ("leben", "Game of Life", "Spiele"),
    ("schild", "Schild", "Helden"),
    ("ironman", "Iron Man", "Helden"),
    ("strange", "Strange Things", "Helden"),
    ("weihnachten", "Weihnachtsgeschichte", "Weihnachten"),
    ("adventskranz", "Adventskranz", "Weihnachten"),
    ("adventskalender", "Adventskalender", "Weihnachten"),
    ("winternacht", "Winternacht", "Weihnachten"),
    ("rentiere", "Rentiere", "Weihnachten"),
    ("kugeln", "Christbaumkugeln", "Weihnachten"),
    ("zuckerstange", "Zuckerstange", "Weihnachten"),
    ("lebkuchen", "Lebkuchentanz", "Weihnachten"),
)
